import Head from "next/head";
import type { AppProps } from "next/app";
import { withLang } from "../useLang";
import { withIsDarkModeEnabled, DarkModeRootStyle, useIsDarkModeEnabled } from "../useIsDarkModeEnabled";

export function App({ Component, pageProps }: AppProps) {


	const { isDarkModeEnabled } = useIsDarkModeEnabled();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="is-dark-mode-enabled" content={`${isDarkModeEnabled}`} />
			</Head>
			<>
				<DarkModeRootStyle />
				<Component {...pageProps} />
			</>
		</>
	);
}

export default withIsDarkModeEnabled(withLang(App));