import Head from "next/head";
import withDarkMode from "next-dark-mode";
import type { AppProps } from "next/app";
import { useDarkMode } from "next-dark-mode";

export function App({ Component, pageProps }: AppProps) {

	const { darkModeActive } = useDarkMode();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="interface mode" content={darkModeActive ? "dark" : "light"} />
			</Head>
			<Component {...pageProps} />
		</>
	);

}

export default withDarkMode(App);